In [16]:
import torch
import torch.nn as nn

In [ ]:
# input
torch.manual_seed(42) # similar to random_state in ML
inputs = torch.tensor([1.0,2.0,3.0])  # should be float values

In [18]:
neuron = nn.Linear(in_features=3,out_features=1)

In [19]:
output = neuron(inputs)

In [20]:
output

tensor([0.2632], grad_fn=<ViewBackward0>)

In [21]:
# verify
neuron.weight @ inputs + neuron.bias


tensor([0.2632], grad_fn=<AddBackward0>)

In [22]:
# To know the weights !
neuron.weight  

Parameter containing:
tensor([[-0.1183, -0.1341,  0.3961]], requires_grad=True)

In [23]:
# To know the bias
neuron.bias

Parameter containing:
tensor([-0.5384], requires_grad=True)